# This file is part of the Home Assistant role.
#
# Copyright (c) 2015-2020 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under Apache 2.0. All rights reserved.
#
---
- include_tasks: preparation.yml
- include_tasks: motd.yml
  when: motd_modification | default(false)
- include_tasks: installation.yml
- include_tasks: systemd.yml
- include_tasks: firewall.yml
  when: ansible_distribution == "Fedora"
