# This file is part of the Home Assistant role.
#
# Copyright (c) 2015-2020 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under Apache 2.0. All rights reserved.
#
---
- name: create user
  user:
    name: "{{ ha_user }}"
    comment: "Home Assistant"
    system: yes
    shell: "/sbin/nologin"
    groups:
      - dialout

- name: create directory
  file:
    path: "{{ ha_conf_dir }}"
    state: directory
    mode: 02775
    owner: "{{ ha_user }}"
    group: "{{ ha_user }}"

- name: install commonly-named packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - gcc

- name: Get stats of /opt/python{{ ha_python_version }}/bin/python3
  stat:
    path: /opt/python{{ ha_python_version }}/bin/python3
  register: st

- name: create directory /opt/python{{ ha_python_version }}
  ansible.builtin.file:
    path: /opt/python{{ ha_python_version }}
    state: directory

- name: unpack python{{ ha_python_version }}
  unarchive:
    src: https://www.python.org/ftp/python/{{ ha_python_version }}/Python-{{ ha_python_version }}.tgz
    dest: /tmp/
    remote_src: yes
    creates: /tmp/Python-{{ ha_python_version }}
  when: st.stat.exists == false  

- name: Running ./configure for python{{ ha_python_version }}
  command: ./configure --prefix=/opt/python{{ ha_python_version }}
  args:
    chdir: /tmp/Python-{{ ha_python_version }}
    creates: /tmp/Python-{{ ha_python_version }}/Makefile
  when: st.stat.exists == false  
- name: Running "make" for python{{ ha_python_version }}  
  make:
    chdir: /tmp/Python-{{ ha_python_version }}
    target: all
    params:
      --jobs: "{{ ha_python_build_jobs }}"
  when: st.stat.exists == false
- name: Running "make install" for python{{ ha_python_version }}  
  make:
    chdir: /tmp/Python-{{ ha_python_version }}
    target: install
  become: true
  when: st.stat.exists == false

- name: install debian-required pip packages
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "{{ ha_conf_dir }}"
    virtualenv_command: /opt/python{{ ha_python_version }}/bin/python3 -m venv
  with_items:
    - appdirs
    - packaging
    - python-dateutil
  when: ansible_distribution == "Debian"
  